name: Tests
on:
  repository_dispatch:
    types: [test]

jobs:
  get-affected:
    name: Get affected projects
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.affected.outputs.affected }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
          repository: ${{ secrets.REPOSITORY }}
          ref: ${{ github.event.client_payload.github.ref }}

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci && npm ci --prefix .github/actions

      - name: Affected
        id: affected
        uses: ./.github/actions/list-affected
        with:
          base: 'origin/test'
          head: 'HEAD'

      - name: Output vars
        run: |
          echo "Affected: ${{ steps.affected.outputs.affected }}"
          echo "Affected JSON: ${{ fromJSON(steps.affected.outputs.affected) }}"

  units:
    name: Unit tests & linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
          repository: ${{ secrets.REPOSITORY }}
          ref: ${{ github.event.client_payload.github.ref }}

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('package-lock.json') }}
          restore-keys: nodemodules-

      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install && npm install @swc/core-linux-x64-gnu

      - name: Setup sqlite
        run: npm run rebuild-sqlite

      - name: Create .env file
        run: |
          echo "TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}" >> .env
          echo "TRELLO_REDIRECT_URL=${{ secrets.TRELLO_REDIRECT_URL }}" >> .env

      - name: Lint
        run: npx nx affected --target=lint --base=origin/test --head=HEAD --parallel=3

      - name: Test
        run: npx nx affected --target=test --base=origin/test --head=HEAD --parallel=3
        env:
          SHORT_BREAK_DURATION_SECONDS: 5
          LONG_BREAK_DURATION_SECONDS: 15
          WORK_DURATION_SECONDS: 10
          LONG_BREAK_INTERVAL: 4
          AUTO_RUN_WORK: false
          AUTO_RUN_BREAK: false
          DB_ENGINE: better-sqlite3
