name: Tests
on:
  repository_dispatch:
    types: [test]

jobs:
  units:
    name: Unit tests & linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
          repository: ${{ secrets.REPOSITORY }}
          ref: ${{ github.event.client_payload.github.ref }}

      - name: Print contents
        run: |
          ls -la
          echo ${{ github.event.client_payload.github }}
